### ISSUE TITLE
[Request] Implement creation of circuit and dialing connections through TOR

### ISSUE THREAD

**Issue by JuniorJPDJ** [mmcloughlin/pearl#2]
Hi,
I can see, you are creating only relay mode of tor.

I tried to do something with your code to make this, but it's to hard for me to understand how it works.

Is it possible for you, to create a "client" mode?
The best would be to have dialer for connections through tor.

**Comment by mmcloughlin** [comment]
@JuniorJPDJ Thanks for your interest in the project.

Can you clarify your use case here? I'm assuming you want to do more than just connect to the Tor network? If that's all you want to do then use the SOCKS proxy https://gist.github.com/mmcloughlin/17e3ca302785f0e525655191d3f9211d

This code currently implements only a tiny subset of the Tor protocol. I will need to implement client mode, but I need to find more time to devote to this project.

I recommend https://github.com/tvdw/gotor for a more complete implementation.

**Comment by JuniorJPDJ** [comment]
Ya, I know how to use tor thorugh socks, but my case needs having tor as a library in my binary. I would like to make tor tcp connection without need to install tor binary and connecting to socks proxy.

I've seen gotor, but it also does not implement OP part of tor

**Comment by mmcloughlin** [comment]
OK I understand, thanks for clarifying. I would like to support this, but I can't promise it any time soon, given progress on this project so far :/

I assume this needs to be Go code too? Does the node.js version have what you need? https://github.com/Ayms/node-Tor. Might be painful, but there's always the core C libraries https://github.com/torproject/tor.

Sorry I can't be more helpful right now.

**Comment by JuniorJPDJ** [comment]
It will be great if it will be language which produces binary, not interpreted or emulated, golang is my first choice just because of results I found for "tor golang" in google :D 
I also don't have enough self-denial to play with this C code.
I've also seen some OP implementations in Python, but it's very old code - mostly not working today.

Thanks for help ;D
